version: '3'

services:
  wordpress:
    image: wordpress:5.4
    ports:
      - 40080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./hello/:/var/www/html/wp-content/plugins/gutenberg-block-hello/

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
